# Generated by Django 5.2.4 on 2025-07-29 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('company_address', models.TextField(blank=True)),
                ('company_email', models.EmailField(blank=True, max_length=254)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
