# services:
#   web:
#     build: .
#     command: >
#       sh -c "
#         python manage.py migrate --noinput &&
#         python manage.py collectstatic --noinput &&
#         gunicorn invoice_generator.wsgi:application --bind 0.0.0.0:8000
#       "
#     volumes:
#       - .:/app
#       - static_volume:/app/staticfiles
#       - media_volume:/app/media
#     ports:
#       - "8000:8000"
#     env_file:
#       - .env

# volumes:
#   static_volume:
#   media_volume:

services:
  web:
    build: .
    command: >
      sh -c "
        python manage.py migrate --noinput &&
        python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env

volumes:
  static_volume:
  media_volume:

  
