# Generated by Django 5.2.4 on 2025-07-29 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicehistory',
            name='company_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
